### ISSUE TITLE
Bring users.get_by_username to the v4 API

### ISSUE THREAD

**Issue by vilhelmen** [python-gitlab/python-gitlab#468]
## Description of the problem, including code/CLI snippet

Looks like `users.get_by_username` didn't make the jump to the v4 API. I see that the docs have been updated to use `list()` with a `username` filter and taking the first element, but it's a little ugly, and to be honest I'm not eager to find/replace everywhere. Is it too much to ask to have it added to the v4 API?

## Expected Behavior
Exists

## Actual Behavior
Doesn't

`'UserManager' object has no attribute 'get_by_username'`

## Specifications

  - python-gitlab version: 1.3.0
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 10.5.3-ee e847016

**Comment by gpocentek** [comment]
Hello @vilhelmen 

I made the choice to only implement the "pure" Gitlab API when adding the v4 support in python-gitlab, so I remove the `get_by_username` method. I know this can be a burden for end user when migrating to v4, but this is also how I can keep the project focused and maintainable within the limited time I have to work on it.
