### ISSUE TITLE
Python 3.7 can't seem to resolve some of the package structure

### ISSUE THREAD

**Issue by jgeorgeson** [python-gitlab/python-gitlab#554]
## Description of the problem, including code/CLI snippet

Amazon's Linux distribution bundles Python 3.7.0 rc1, and it seems to be unable to resolve classes in `gitlab.v4.objects`. 

```python
$ python3
Python 3.7.0rc1 (default, Jun 20 2018, 02:13:35) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> def myfunc(param: gitlab.v4.objects.Group):
...     return true
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gitlab.v4' has no attribute 'objects'
>>> 
```

## Specifications

  - python-gitlab version: 1.5.1, python 3.7.0rc1
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): 10.7.5

**Comment by jgeorgeson** [comment]
Hm, I was certain I had tested that it worked with Python 3.4/3.6 on CentOS 7, but I am seeing the same failure now. The [python-guide](http://docs.python-guide.org/en/latest/writing/structure/) seems to favor importing the base module and using qualified references to subpackages, but I don't see reference to typing function parameters. Would recommend just not using type hints on function parameters then?

**Comment by gpocentek** [comment]
I'm not sure at all what the best practice is, I've seen good arguments in favour of different import methods.

Since you can import `gitlab.v4.objects` you should be able to use the typed function parameter.
