### ISSUE TITLE
Type hints: add `py.typed` marker

### ISSUE THREAD

**Issue by bersbersbers** [python-gitlab/python-gitlab#2715]
## Description of the problem, including code/CLI snippet

```
(.venv) C:\Build\project>echo import gitlab > bug.py

(.venv) C:\Build\project>mypy bug.py
```

## Expected Behavior

No `mypy` error

## Actual Behavior

```
bug.py:1: error: Skipping analyzing "gitlab": module is installed, but missing library stubs or py.typed marker  [import-untyped]
bug.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
bug.py:1: note: See https://mypy.rtfd.io/en/stable/_refs.html#code-import-untyped for more info
Found 1 error in 1 file (checked 1 source file)
```

## Specifications

  - python-gitlab version: 4.1.0 and 4.0.0 (not before 4)
  - API version you are using (v3/v4): n/a
  - Gitlab server version (or gitlab.com): n/a

## Relevant info

> Mypy will not try inferring the types of any 3rd party libraries you have installed unless they either have declared themselves to be [PEP 561 compliant stub package](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages) (e.g. with a py.typed file) or have registered themselves on [typeshed](https://github.com/python/typeshed), the repository of types for the standard library and some 3rd party libraries.

https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

And in fact, `echo > .venv\Lib\site-packages\gitlab\py.typed` fixes the problem for me.

**Comment by bersbersbers** [comment]
If anyone is wondering, other major libraries are doing that, too:
- https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/py.typed
- https://github.com/numpy/numpy/blob/main/numpy/py.typed

**Comment by bersbersbers** [comment]
I thinks this is a regression caused by https://github.com/python-gitlab/python-gitlab/commit/71fca8c8f5c7f3d6ab06dd4e6c0d91003705be09.

Versions before had

https://github.com/python-gitlab/python-gitlab/blob/59d6a880aacd7cf6f443227071bb8288efb958c4/setup.py#L36-L38

but `py.typed` is missing in the new `pyproject.toml`.

**Comment by nejch** [comment]
@bersbersbers yes that's definitely a regression in the build change here, thanks for the report!

**Comment by nejch** [comment]
@bersbersbers https://pypi.org/project/python-gitlab/4.1.1/ should be fine, but please let us know otherwise!

**Comment by bersbersbers** [comment]
Thanks - works great!
